workflows:
  ios-build:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean project
        script: flutter clean
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: Encrypted(...)
